# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from langbot_plugin.api.definition.components.common.event_listener import EventListener
from langbot_plugin.api.entities import events, context


class DefaultEventListener(EventListener):

    async def initialize(self):
        await super().initialize()
        
        "Fill with your code here"
        @self.handler(events.PersonMessageReceived)
        async def handler(event_context: context.EventContext):
            print("Hello LangBot Plugin!")
            print(event_context)
            
            await event_context.reply(
                platform_message.MessageChain([
                    platform_message.Plain(text=f"Hello from Nahida Plugin!"),
                ])
            )

            @self.handler(events.GroupMessageReceived)
            async def handlerGroup(event_context: context.EventContext):
                print("Hello LangBot Plugin!")
                print(event_context)
                
                await event_context.reply(
                    platform_message.MessageChain([
                        platform_message.Plain(text=f"Hello from Nahida Plugin!"),
                    ])
                )