apiVersion: v1
kind: Command
metadata:
  name: info
  label:
    en_US: Info
    zh_Hans: Info
  description:
    en_US: '查询价格'
    zh_Hans: '查询价格'
spec:
execution:
  python:
    path: info.py
    attr: Info